### PR TITLE
Update for GNOME 45

### PR DESCRIPTION
**Pull request by slaclau**
This is my initial update for GNOME 45, the extension works but needs some tidying

### CODE REVIEW

**Comment by slaclau** [comment]
I have also implemented additional functionality in the preferences dialogue, and added suspend then hibernate

**Comment by slaclau** [comment]
This also addresses the following: #2 #23 #78 #92 #104

**Comment by p91paul** [comment]
Thanks! I will test and release on e.g.o. in a few days.

**Comment by p91paul** [comment]
@slaclau are you interested in becoming this extension mantainer? I am having trouble finding the time to continue maintaining this, and to be honest I basically do not hibernate my system anymore. It involves both taking care of continued functionality here and upload of new versions to extensions.gnome.org.

**Comment by slaclau** [comment]
Sure, I’d be happy toOn 14 Oct 2023, at 20:04, Paolo Inaudi ***@***.***> wrote:﻿
@slaclau are you interested in becoming this extension mantainer? I am having trouble finding the time to continue maintaining this, and to be honest I basically do not hibernate my system anymore. It involves both taking care of continued functionality here and upload of new versions to extensions.gnome.org.

**Comment by p91paul** [comment]
@arelange can you add @slaclau as a contributor?

**Pull request merged**
