### PR TITLE
Update for Gnome 3.16

### PR DESCRIPTION
**Pull request by Anthony25**
Hello,
I tested your addon on 3.16, and it seems to be compatible !

### CODE REVIEW

**Comment by michalrus** [comment]
:+1:

**Comment by Anthony25** [comment]
A little review after a month on Gnome 3.16: no problem with your add on, and no errors shown by the looking glass.

**Comment by michalrus** [comment]
Same here.

**Comment by Anthony25** [comment]
The modification has just be done by @arelange, so I'm closing this pull request.

@arelange: Thanks for adding me as a maintainer !

**Pull request closed without merging**
